name: Release
on:
  push: { tags: 'v[0-9]+.[0-9]+.[0-9]+' }

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: script/release-notes | tee relnotes.txt
      - uses: olegtarasov/get-tag@v1
        id: tagname
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: node-build ${{ steps.tagname.outputs.tag }}
          body_path: relnotes.txt

  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1.4
        with:
          formula-name: node-build
        env:
          COMMITTER_TOKEN: ${{ secrets.REPO_TOKEN }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          scope: '@nodenv'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
